use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Name of the RSpec formatter class the generated `.rspec-local` loads.
const FORMATTER_CLASS: &str = "AgentMonitorRspecFormatter";

/// Resolves the RSpec formatter's installed path relative to this binary's
/// own location, rather than a version-pinned path, so a `.rspec-local`
/// generated by an older version still resolves after a `brew upgrade` (see
/// design.md's "path resolution" decision and the rspec-test-reporting
/// spec's "stable path across upgrades" requirement). Homebrew installs
/// `bin/agentmon` and `share/agent-monitor/...` under the same stable
/// `opt_prefix` symlink directory, so `bin/../share/...` relative to the
/// running binary stays correct across versions.
pub fn formatter_path() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let bin_dir = exe.parent()?;
    Some(
        bin_dir
            .join("..")
            .join("share")
            .join("agent-monitor")
            .join("rspec_formatter.rb"),
    )
}

/// The `--require`/`--format` line this subcommand ensures is present in a
/// project's `.rspec-local`, pointing at `formatter_path`.
fn rspec_local_line(formatter_path: &Path) -> String {
    format!(
        "--require '{}' --format {FORMATTER_CLASS} --format progress",
        formatter_path.display()
    )
}

/// Writes (or idempotently updates) `.rspec-local` in `dir` so RSpec loads
/// the formatter at `formatter_path`, without touching `.rspec`. Existing
/// content in `.rspec-local` is preserved; the line is only appended if not
/// already present.
pub fn write_rspec_local(dir: &Path, formatter_path: &Path) -> io::Result<()> {
    let path = dir.join(".rspec-local");
    let line = rspec_local_line(formatter_path);

    let existing = fs::read_to_string(&path).unwrap_or_default();
    if existing.lines().any(|l| l == line) {
        return Ok(());
    }

    let mut updated = existing;
    if !updated.is_empty() && !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str(&line);
    updated.push('\n');

    fs::write(path, updated)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn unique_dir(tag: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!(
            "agentmon-init-rspec-test-{tag}-{}-{nanos}",
            std::process::id()
        ));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn creates_rspec_local_when_none_exists() {
        let dir = unique_dir("fresh");
        let formatter = PathBuf::from("/opt/agent-monitor/share/agent-monitor/rspec_formatter.rb");

        write_rspec_local(&dir, &formatter).unwrap();

        let written = fs::read_to_string(dir.join(".rspec-local")).unwrap();
        assert!(written.contains(&rspec_local_line(&formatter)));
    }

    #[test]
    fn does_not_touch_rspec() {
        let dir = unique_dir("leaves-rspec-alone");
        fs::write(dir.join(".rspec"), "--color\n").unwrap();
        let formatter = PathBuf::from("/opt/agent-monitor/share/agent-monitor/rspec_formatter.rb");

        write_rspec_local(&dir, &formatter).unwrap();

        assert_eq!(fs::read_to_string(dir.join(".rspec")).unwrap(), "--color\n");
    }

    #[test]
    fn running_twice_does_not_duplicate_the_line() {
        let dir = unique_dir("idempotent");
        let formatter = PathBuf::from("/opt/agent-monitor/share/agent-monitor/rspec_formatter.rb");

        write_rspec_local(&dir, &formatter).unwrap();
        write_rspec_local(&dir, &formatter).unwrap();

        let written = fs::read_to_string(dir.join(".rspec-local")).unwrap();
        let occurrences = written.matches(&rspec_local_line(&formatter)).count();
        assert_eq!(occurrences, 1, "re-running must not duplicate the line");
    }

    #[test]
    fn preserves_unrelated_existing_content() {
        let dir = unique_dir("preserve");
        fs::write(dir.join(".rspec-local"), "--format documentation\n").unwrap();
        let formatter = PathBuf::from("/opt/agent-monitor/share/agent-monitor/rspec_formatter.rb");

        write_rspec_local(&dir, &formatter).unwrap();

        let written = fs::read_to_string(dir.join(".rspec-local")).unwrap();
        assert!(written.contains("--format documentation"));
        assert!(written.contains(&rspec_local_line(&formatter)));
    }
}
