require "socket"
require "json"
require "timeout"

# Reports an RSpec run's start/pass/fail lifecycle to agentd, correlated by
# working directory rather than any Claude Code session id - see
# openspec/specs/rspec-test-reporting/spec.md. Loaded via a project's
# .rspec-local, generated by `agentmon init-rspec`.
class AgentMonitorRspecFormatter
  RSpec::Core::Formatters.register self, :start, :dump_summary

  # Bounds how long a socket send can block, mirroring agentmon-report's
  # SEND_TIMEOUT: reporting must never make a test run wait on a hung or
  # unreachable daemon.
  SEND_TIMEOUT = 0.5

  def initialize(output)
    @output = output
  end

  def start(_notification)
    report("started")
  end

  def dump_summary(summary)
    report(summary.failure_count.zero? ? "passed" : "failed")
  end

  private

  def report(status)
    Timeout.timeout(SEND_TIMEOUT) do
      socket = UNIXSocket.new(socket_path)
      begin
        socket.write("#{payload(status)}\n")
      ensure
        socket.close
      end
    end
  rescue StandardError
    # Sending must never raise or otherwise affect the run - the daemon may
    # not be running, and that must be indistinguishable from this formatter
    # not being loaded at all.
  end

  def payload(status)
    JSON.generate(
      "type" => "report_test_run",
      "cwd" => Dir.pwd,
      "pid" => Process.pid,
      "status" => status
    )
  end

  # ~/Library/Application Support/agentmon/agentd.sock, matching
  # agentmon_proto::default_socket_path - kept in sync by hand since this
  # formatter has no dependency on the Rust crate. Overridable via
  # AGENTMON_SOCKET_PATH so this formatter's own test suite can point it at
  # a temporary mock listener instead of a real daemon.
  def socket_path
    ENV["AGENTMON_SOCKET_PATH"] ||
      File.join(Dir.home, "Library", "Application Support", "agentmon", "agentd.sock")
  end
end
